<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EquipmentsSeeder extends Seeder
{
    public function run()
    {
        DB::table('equipments')->insert([
            [
                'code' => 'E001',
                'name' => 'Máy đo tim thai cá nhân Jumper JPD-100E',
                'equipment_type_code' => 'ET001',
                'unit_code' => 'UNIT001',
                'price' => 1687000,
                'country' => 'Mỹ',
                'supplier_code' => 'SUP001',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'code' => 'E002',
                'name' => 'Máy đo nồng độ oxy máu và nhịp tim Jumper JPD-500D (LED)',
                'equipment_type_code' => 'ET002',
                'unit_code' => 'UNIT010',
                'price' => 801000,
                'country' => 'Việt Nam',
                'supplier_code' => 'SUP001',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'code' => 'E003',
                'name' => 'Máy đo huyết áp bắp tay Jumper JPD-HA210',
                'equipment_type_code' => 'ET003',
                'unit_code' => 'UNIT007',
                'price' => 711000,
                'country' => 'Trung Quốc',
                'supplier_code' => 'SUP001',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'code' => 'E004',
                'name' => 'Nhiệt kế hồng ngoại không tiếp xúc Jumper FR202',
                'equipment_type_code' => 'ET004',
                'unit_code' => 'UNIT001',
                'price' => 675000,
                'country' => 'Đức',
                'supplier_code' => 'SUP001',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'code' => 'E005',
                'name' => 'Cân điện tử Beurer GS10',
                'equipment_type_code' => 'ET001',
                'unit_code' => 'UNIT001',
                'price' => 580000,
                'country' => 'Nhật Bản',
                'supplier_code' => 'SUP001',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'code' => 'E006',
                'name' => 'Máy đo huyết áp cổ tay OMRON 6121',
                'equipment_type_code' => 'ET001',
                'unit_code' => 'UNIT001',
                'price' => 675000,
                'country' => 'Nhật Bản',
                'supplier_code' => 'SUP001',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'code' => 'E007',
                'name' => 'MN-MDHA8712 - Máy đo huyết áp HEM-8712',
                'equipment_type_code' => 'ET001',
                'unit_code' => 'UNIT001',
                'price' => 940000,
                'country' => 'Nhật Bản',
                'supplier_code' => 'SUP001',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'code' => 'E008',
                'name' => 'GIƯỜNG Y TẾ ĐA CHỨC NĂNG A07 (Có xe lăn tách rời)',
                'equipment_type_code' => 'ET001',
                'unit_code' => 'UNIT001',
                'price' => 10000000,
                'country' => 'Nhật Bản',
                'supplier_code' => 'SUP001',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'code' => 'E009',
                'name' => 'Giường y tế đa chức năng, model: D01-S',
                'equipment_type_code' => 'ET001',
                'unit_code' => 'UNIT001',
                'price' => 16500000,
                'country' => 'Nhật Bản',
                'supplier_code' => 'SUP001',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'code' => 'E010',
                'name' => 'TỦ Y TẾ ĐẦU GIƯỜNG - D25',
                'equipment_type_code' => 'ET001',
                'unit_code' => 'UNIT001',
                'price' => 160000,
                'country' => 'Nhật Bản',
                'supplier_code' => 'SUP001',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'code' => 'E011',
                'name' => 'MN-KWD808I- MÁY CHÂM CỨU MODEL KWD-808-I (Yingdi – Trung Quốc)',
                'equipment_type_code' => 'ET001',
                'unit_code' => 'UNIT001',
                'price' => 150000,
                'country' => 'Trung Quốc',
                'supplier_code' => 'SUP001',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'code' => 'E012',
                'name' => 'Máy hiệu ứng từ YF-T08A',
                'equipment_type_code' => 'ET001',
                'unit_code' => 'UNIT001',
                'price' => 350000,
                'country' => 'Trung Quốc',
                'supplier_code' => 'SUP001',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
        ]);
    }
}